/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversordemonedas;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class ConversorMonedas extends javax.swing.JFrame {

    /**
     * Creates new form ConversorMonedas
     */
    public ConversorMonedas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelTXTCONVERTIR = new javax.swing.JLabel();
        jTextFieldMonedaAconvertir = new javax.swing.JTextField();
        jComboBoxMonedaAconvertir = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxConversionaEstaDivisa = new javax.swing.JComboBox<>();
        jButtonConvertir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldGradosAConvertir = new javax.swing.JTextField();
        jComboBoxdGradosAConvertir = new javax.swing.JComboBox<>();
        jLabelA = new javax.swing.JLabel();
        jComboBoxConvertirAEste = new javax.swing.JComboBox<>();
        jLabelResultadosGrados = new javax.swing.JLabel();
        jLabelResultadoImpreso = new javax.swing.JLabel();
        jButtonConvertir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONVERSOR \nDE \nDIVISAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 90));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CREADO POR: OSCAR JAVIER AYON ESCALANTE");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("#ALURALATAM #ORACLE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(552, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 600));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 10, 600));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTXTCONVERTIR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTXTCONVERTIR.setText("CONVERTIR");
        jPanel3.add(jLabelTXTCONVERTIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 240, 40));

        jTextFieldMonedaAconvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMonedaAconvertirActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldMonedaAconvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 90, -1));

        jComboBoxMonedaAconvertir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PESO MEXICANO", "DOLAR", "EURO", "LIBRAS EXTERLINAS", "YEN JAPONES", "WON SUL-COREANO" }));
        jPanel3.add(jComboBoxMonedaAconvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 150, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("A");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 240, 40));

        jComboBoxConversionaEstaDivisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PESO MEXICANO", "DOLAR", "EURO", "LIBRAS EXTERLINAS", "YEN JAPONES", "WON SUL-COREANO" }));
        jPanel3.add(jComboBoxConversionaEstaDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 240, -1));

        jButtonConvertir.setText("CONVERTIR");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("RESULTADO DE CONVERSION");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 230, 30));

        jLabelResultado.setBackground(new java.awt.Color(204, 204, 255));
        jLabelResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel3.add(jLabelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 230, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 510, 20));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CONVERTIR GRADOS");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 240, 40));

        jTextFieldGradosAConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGradosAConvertirActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldGradosAConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 90, -1));

        jComboBoxdGradosAConvertir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CELCIUS", "FARENHEIT" }));
        jPanel3.add(jComboBoxdGradosAConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 150, -1));

        jLabelA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelA.setText("A");
        jPanel3.add(jLabelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 240, 40));

        jComboBoxConvertirAEste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FARENHEIT", "CELCIUS" }));
        jPanel3.add(jComboBoxConvertirAEste, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 240, -1));

        jLabelResultadosGrados.setBackground(new java.awt.Color(204, 204, 255));
        jLabelResultadosGrados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultadosGrados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel3.add(jLabelResultadosGrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 230, 30));

        jLabelResultadoImpreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultadoImpreso.setText("RESULTADO DE CONVERSION");
        jPanel3.add(jLabelResultadoImpreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 230, 30));

        jButtonConvertir1.setText("CONVERTIR");
        jButtonConvertir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertir1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonConvertir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 510, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMonedaAconvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMonedaAconvertirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMonedaAconvertirActionPerformed

    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
        
        if(jTextFieldGradosAConvertir.getText().length()==0){
            
            JOptionPane.showMessageDialog(null,"No ha colocado los grados a convertir");
            
        }else{
        
            if(jComboBoxdGradosAConvertir.getSelectedItem() == jComboBoxConvertirAEste.getSelectedItem()){
                
                JOptionPane.showMessageDialog(null,"No se puede convertir entre la misma");
                
            }else{
                if(jComboBoxdGradosAConvertir.getSelectedItem() == "CELCIUS"){
                    double resultado;
                    double grados = Double.parseDouble(jTextFieldGradosAConvertir.getText());
                    resultado = (grados*1.8)+32;
                    jLabelResultadosGrados.setText(resultado+"° Farenheit");
                }else{
                    double resultado;
                    double grados = Double.parseDouble(jTextFieldGradosAConvertir.getText());
                    resultado = (grados-32)/1.8;
                    jLabelResultadosGrados.setText(resultado+"° Celcius");
                }
                
            }
            
        }
        
    }//GEN-LAST:event_jButtonConvertirActionPerformed

    private void jTextFieldGradosAConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGradosAConvertirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGradosAConvertirActionPerformed

    private void jButtonConvertir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConvertir1ActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorMonedas().setVisible(true);
            }
        });
    }
    
    
    
    public void conversion(double cantidad,double precioMoneda){
            double resultado;
            cantidad = Double.parseDouble(jTextFieldMonedaAconvertir.getText());
            //VALOR DE PESO MEXICANO ES 0.050 FRENTE A LIBRA EXTERLINA A LA FECHA DE CREACION DE ESTE PROYECTO 
            resultado = precioMoneda * cantidad;
            jLabelResultado.setText(""+resultado);
    }
    
    public void mexicano(){
        //comparar si ambos nombres de divisas son iguales
        if(jComboBoxMonedaAconvertir.getSelectedItem()==jComboBoxConversionaEstaDivisa.getSelectedItem()){
            JOptionPane.showMessageDialog(null,"No se puede convertir la divisa en si misma");
        }
        
        //comparar si la casilla de cantidad está vacia
        if(jTextFieldMonedaAconvertir.getText().length()==0){
            JOptionPane.showMessageDialog(null,"No colocaste la cantidad a convertir");
        }
        
        //convertir peso mexicano a dolar
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="PESO MEXICANO" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="DOLAR"){
            //VALOR DE PESO MEXICANO ES 0.054 FRENTE AL DOLAR A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.054);
        }
        
        //convertir peso mexicano a EURO
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="PESO MEXICANO" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="EURO"){
            //VALOR DE PESO MEXICANO ES 0.050 FRENTE AL EURO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.050);
        }
        
        //convertir peso mexicano a LIBRAS EXTERLINAS
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="PESO MEXICANO" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="LIBRAS EXTERLINAS"){
            //VALOR DE PESO MEXICANO ES 0.044 FRENTE A LIBRAS EXTERLINAS A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.044);
        }
        
        //convertir peso mexicano a YEN JAPONES
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="PESO MEXICANO" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="YEN JAPONES"){
            //VALOR DE PESO MEXICANO ES 7.07 FRENTE A YEN JAPONES A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),7.07);
        }
        
        //convertir peso mexicano a WON SUL-COREANO
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="PESO MEXICANO" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="WON SUL-COREANO"){
            //VALOR DE PESO MEXICANO ES 70.12 FRENTE A WON SUL-COREANO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),70.12);
        }
    }
    
    public void dolar(){
        //comparar si ambos nombres de divisas son iguales
        if(jComboBoxMonedaAconvertir.getSelectedItem()==jComboBoxConversionaEstaDivisa.getSelectedItem()){
            JOptionPane.showMessageDialog(null,"No se puede convertir la divisa en si misma");
        }
        
        //comparar si la casilla de cantidad está vacia
        if(jTextFieldMonedaAconvertir.getText().length()==0){
            JOptionPane.showMessageDialog(null,"No colocaste la cantidad a convertir");
        }
        
        //convertir dolar a peso mexicano
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="DOLAR" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="PESO MEXICANO"){
            //VALOR DE DOLAR ES 18.44 FRENTE AL PESO MEXICANO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),18.44);
        }
        
        //convertir dolar a EURO
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="DOLAR" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="EURO"){
            //VALOR DE DOLAR ES 0.93 FRENTE A AL EURO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.93);
        }
        
        //convertir dolar a LIBRAS EXTERLINAS
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="DOLAR" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="LIBRAS EXTERLINAS"){
            //VALOR DE DOLAR ES 0.82 FRENTE A LIBRAS EXTERLINAS A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.82);
        }
        
        //convertir dolar a YEN JAPONES
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="DOLAR" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="YEN JAPONES"){
            //VALOR DE DOLAR ES 130.75 FRENTE A YEN JAPONES A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),130.75);
        }
        
        //convertir dolar a WON SUL-COREANO
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="DOLAR" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="WON SUL-COREANO"){
            //VALOR DE DOLAR ES 1292.90 FRENTE A WON SUL-COREANO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),1292.90);
        }
    }
    
    public void euro(){
        //comparar si ambos nombres de divisas son iguales
        if(jComboBoxMonedaAconvertir.getSelectedItem()==jComboBoxConversionaEstaDivisa.getSelectedItem()){
            JOptionPane.showMessageDialog(null,"No se puede convertir la divisa en si misma");
        }
        
        //comparar si la casilla de cantidad está vacia
        if(jTextFieldMonedaAconvertir.getText().length()==0){
            JOptionPane.showMessageDialog(null,"No colocaste la cantidad a convertir");
        }
        
        //convertir euro a peso mexicano
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="EURO" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="PESO MEXICANO"){
            //VALOR DEL EURO ES 19.82 FRENTE AL PESO MEXICANO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),19.82);
        }
        
        //convertir euro a DOLAR
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="EURO" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="DOLAR"){
            //VALOR DEL EURO ES 1.08 FRENTE A AL EURO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),1.08);
        }
        
        //convertir euro a LIBRAS EXTERLINAS
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="EURO" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="LIBRAS EXTERLINAS"){
            //VALOR DEL EURO ES 0.89 FRENTE A LIBRAS EXTERLINAS A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.89);
        }
        
        //convertir euro a YEN JAPONES
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="EURO" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="YEN JAPONES"){
            //VALOR DEL EURO ES 140.67 FRENTE A YEN JAPONES A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),140.67);
        }
        
        //convertir euro a WON SUL-COREANO
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="EURO" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="WON SUL-COREANO"){
            //VALOR DEL EURO ES 1394.41 FRENTE A WON SUL-COREANO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),1394.41);
        }
    }
    
    public void librasExterlinas(){
        //comparar si ambos nombres de divisas son iguales
        if(jComboBoxMonedaAconvertir.getSelectedItem()==jComboBoxConversionaEstaDivisa.getSelectedItem()){
            JOptionPane.showMessageDialog(null,"No se puede convertir la divisa en si misma");
        }
        
        //comparar si la casilla de cantidad está vacia
        if(jTextFieldMonedaAconvertir.getText().length()==0){
            JOptionPane.showMessageDialog(null,"No colocaste la cantidad a convertir");
        }
        
        //convertir libra exterlina a peso mexicano
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="LIBRAS EXTERLINAS" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="PESO MEXICANO"){
            //VALOR DE LIBRA EXTERLINA ES 22.55 FRENTE AL PESO MEXICANO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),22.55);
        }
        
        //convertir libra exterlina a DOLAR
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="LIBRAS EXTERLINAS" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="DOLAR"){
            //VALOR DE LIBRA EXTERLINA ES 1.22 FRENTE A AL EURO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),1.22);
        }
        
        //convertir libra exterlina a EURO
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="LIBRAS EXTERLINAS" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="LIBRAS EXTERLINAS"){
            //VALOR DE LIBRA EXTERLINA ES 1.13 FRENTE A LIBRAS EXTERLINAS A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),1.13);
        }
        
        //convertir libra exterlina a YEN JAPONES
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="LIBRAS EXTERLINAS" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="YEN JAPONES"){
            //VALOR DE LIBRA EXTERLINA ES 140.67 FRENTE A YEN JAPONES A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),159.87);
        }
        
        //convertir libra exterlina a WON SUL-COREANO
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="LIBRAS EXTERLINAS" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="WON SUL-COREANO"){
            //VALOR DE LIBRA EXTERLINA ES 1584.39 FRENTE A WON SUL-COREANO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),1584.39);
        }
    }
    
    public void yenJapones(){
        //comparar si ambos nombres de divisas son iguales
        if(jComboBoxMonedaAconvertir.getSelectedItem()==jComboBoxConversionaEstaDivisa.getSelectedItem()){
            JOptionPane.showMessageDialog(null,"No se puede convertir la divisa en si misma");
        }
        
        //comparar si la casilla de cantidad está vacia
        if(jTextFieldMonedaAconvertir.getText().length()==0){
            JOptionPane.showMessageDialog(null,"No colocaste la cantidad a convertir");
        }
        
        //convertir yen japones a peso mexicano
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="YEN JAPONES" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="PESO MEXICANO"){
            //VALOR DE YEN JAPONES ES 0.14 FRENTE AL PESO MEXICANO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.14);
        }
        
        //convertir yen japones a DOLAR
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="YEN JAPONES" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="DOLAR"){
            //VALOR DE YEN JAPONES ES 0.0076 FRENTE AL DOLAR A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.0076);
        }
        
        //convertir yen japones a EURO
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="YEN JAPONES" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="EURO"){
            //VALOR DE YEN JAPONES ES 0.0071 FRENTE A LIBRAS EXTERLINAS A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.0071);
        }
        
        //convertir yen japones a libra exterlina
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="YEN JAPONES" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="LIBRAS EXTERLINAS"){
            //VALOR DE YEN JAPONES ES 0.0062 FRENTE A LIBRA EXTERLINA A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.0062);
        }
        
        //convertir yen japones a WON SUL-COREANO
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="YEN JAPONES" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="WON SUL-COREANO"){
            //VALOR DE YEN JAPONES ES 9.87 FRENTE A WON SUL-COREANO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),9.87);
        }
    }
    
    public void wonSulcoreano(){
        //comparar si ambos nombres de divisas son iguales
        if(jComboBoxMonedaAconvertir.getSelectedItem()==jComboBoxConversionaEstaDivisa.getSelectedItem()){
            JOptionPane.showMessageDialog(null,"No se puede convertir la divisa en si misma");
        }
        
        //comparar si la casilla de cantidad está vacia
        if(jTextFieldMonedaAconvertir.getText().length()==0){
            JOptionPane.showMessageDialog(null,"No colocaste la cantidad a convertir");
        }
        
        //convertir won-sulcoreano a peso mexicano
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="YEN JAPONES" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="PESO MEXICANO"){
            //VALOR DE WON-SULCOREANO ES 0.014 FRENTE AL PESO MEXICANO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.014);
        }
        
        //convertir won-sulcoreano a DOLAR
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="YEN JAPONES" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="DOLAR"){
            //VALOR DE WON-SULCOREANO ES 0.00077 FRENTE AL DOLAR A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.0076);
        }
        
        //convertir won-sulcoreano a EURO
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="YEN JAPONES" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="EURO"){
            //VALOR DE WON-SULCOREANO ES 0.00071 FRENTE A LIBRAS EXTERLINAS A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.0071);
        }
        
        //convertir won-sulcoreano a libra exterlina
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="YEN JAPONES" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="LIBRAS EXTERLINAS"){
            //VALOR DE WON-SULCOREANO ES 0.00063 FRENTE A LIBRA EXTERLINA A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.00063);
        }
        
        //convertir won-sulcoreano a yen japones
        if(jComboBoxMonedaAconvertir.getSelectedItem()=="YEN JAPONES" && jComboBoxConversionaEstaDivisa.getSelectedItem()=="YEN JAPONES"){
            //VALOR DE WON-SULCOREANO ES 0.10 FRENTE A WON SUL-COREANO A LA FECHA DE CREACION DE ESTE PROYECTO 
            conversion(Double.parseDouble(jTextFieldMonedaAconvertir.getText()),0.10);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JButton jButtonConvertir1;
    private javax.swing.JComboBox<String> jComboBoxConversionaEstaDivisa;
    private javax.swing.JComboBox<String> jComboBoxConvertirAEste;
    private javax.swing.JComboBox<String> jComboBoxMonedaAconvertir;
    private javax.swing.JComboBox<String> jComboBoxdGradosAConvertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelResultadoImpreso;
    private javax.swing.JLabel jLabelResultadosGrados;
    private javax.swing.JLabel jLabelTXTCONVERTIR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldGradosAConvertir;
    private javax.swing.JTextField jTextFieldMonedaAconvertir;
    // End of variables declaration//GEN-END:variables
}
